### ISSUE TITLE
Where do I find "rebuild_federate.sh" script for Rebuild Configuration

### ISSUE THREAD

**Issue by SafrasIqbal** [mosaic-addons/omnetpp-federate#2]
Hello,

I am following setting up the Omnetpp IDE by following the doc [here](https://www.eclipse.org/mosaic/docs/extending_mosaic/omnetpp_details/). However, I don't find the file rebuild_federate.sh. Where do I get this file or what alternative options that I have.  Please help thank you.

**Comment by kschrab** [comment]
The `rebuild_federate.sh` is back in https://github.com/eclipse/mosaic/tree/main/bundle/src/assembly/resources/fed/omnetpp
